# Generated by Django 3.0.4 on 2020-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_worldborder2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='FIPS Code'),
        ),
    ]
